queue_rules:
  - name: default
    merge_conditions: []

pull_request_rules:
  - name: queue when the body asks for it
    conditions:
      - body~=AUTOMERGE-PLEASE
    actions:
      queue:
        name: default
